### ISSUE TITLE
Add support for unsigned integers

### ISSUE THREAD

**Issue by Zylann** [anhero/JsonBox#16]
When I try to serialize unsigned integers, it results in an ambiguous call (bool, char*, int), and I'm forced to cast them as signed integers (int) to have a perfect match.

**Comment by madbranch** [comment]
Currently, the Value class only contains int values. I could add getUnsignedInteger and setUnsignedInteger, but it would hide some lost of data while converting from an unsigned integer to an integer. To not lose any data, I would need to add a new value to the Type enum in the Value class.

**Comment by madbranch** [comment]
I decided not to add a new value type for unsigned integers in the Value class because it would not make it really better than simply casting. When deserializing, I would have no clue whether the value should be read as a signed or unsigned integer. For sanity and clarity, I'll keep the signed integer only in the Value class.
